name: blog

on: [push]

jobs:
    deploy:
        env:
          HUGO_VERSION: ${{ github.sha }}
          TZ: Asia/Shanghai
        runs-on: ubuntu-latest
        
        steps:
            - name: Git checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
                submodules: true
            
            - name: Set git config core.quotepath false # https://github.com/gohugoio/hugo/issues/9810#issuecomment-1107519804
              run: git config --global core.quotepath false

            - name: Setup hugo
              uses: peaceiris/actions-hugo@v3
              with:
                hugo-version: '0.146.0'
                extended: true

            - name: Build Hugo
              run: hugo
              
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                personal_token: ${{ secrets.TOKEN }}
                external_repository: "blogj/blogj.github.io"
                publish_branch: main
                publish_dir: ./public
                force_orphan: true
                user_name: blogj
                user_email: i@gao4.top
